name: Build package index

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # This will also trigger on merges to the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get GitHub Build Number (ENV)
        id: get_buildno
        run: echo "GITHUBBUILDNUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install Python dependencies
        run: |
          pipenv install

      - name: Fetch packages and build index
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: pipenv run make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build/packages
